//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Halloumi.Abettor.Plugins.WallpaperChanger.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string WallpaperFolder {
            get {
                return ((string)(this["WallpaperFolder"]));
            }
            set {
                this["WallpaperFolder"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("60")]
        public int WallpaperChangeFrequency {
            get {
                return ((int)(this["WallpaperChangeFrequency"]));
            }
            set {
                this["WallpaperChangeFrequency"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ApplyMedianFilter {
            get {
                return ((bool)(this["ApplyMedianFilter"]));
            }
            set {
                this["ApplyMedianFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool CropWallpaper {
            get {
                return ((bool)(this["CropWallpaper"]));
            }
            set {
                this["CropWallpaper"] = value;
            }
        }
    }
}
