//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace Halloumi.Abettor.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("PowderBlue")]
        public Color HighCPUColour {
            get {
                return ((Color)(this["HighCPUColour"]));
            }
            set {
                this["HighCPUColour"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("DarkBlue")]
        public Color LowCPUColour {
            get {
                return ((Color)(this["LowCPUColour"]));
            }
            set {
                this["LowCPUColour"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("DimGray")]
        public Color RAMColour {
            get {
                return ((Color)(this["RAMColour"]));
            }
            set {
                this["RAMColour"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color BackColour {
            get {
                return ((Color)(this["BackColour"]));
            }
            set {
                this["BackColour"] = value;
            }
        }
    }
}
